name: Build jar

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip
        run: unzip -o *.zip

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 6.9

      - name: Build mod
        run: |
          cd EnternalVisuals
          gradle build

      - uses: actions/upload-artifact@v4
        with:
          name: EnternalVisuals-jar
          path: EnternalVisuals/build/libs/*.jar
